## 1. Create a null vector of size 10 but the fifth value which is 1

In [1]:
import numpy as np
null = np.zeros(10)
null[4] = 1
null

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

## 2. Create a vector with values ranging from 10 to 49.

In [3]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## 3. Create a 3x3 matrix with values ranging from 0 to 8

In [4]:
matrix = np.arange(0,9)
matrix .reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [5]:
array = np.array([1,2,0,0,4,0])
np.nonzero(array)

(array([0, 1, 4], dtype=int64),)

## 5. Create a 10x10 array with random values and find the minimum and maximum values.

In [7]:
array_ten = np.random.random((10,10))
print(array_ten)
print(np.min(array_ten))
print(np.max(array_ten))

[[0.37733365 0.51709669 0.05354886 0.43686931 0.14167573 0.7267741
  0.63311304 0.83379587 0.94760964 0.01560271]
 [0.15943543 0.40281834 0.4269547  0.88098377 0.23941701 0.89018234
  0.48155017 0.00616316 0.95460008 0.92495155]
 [0.42297023 0.84847054 0.77569962 0.15564543 0.9039857  0.8780154
  0.8487104  0.64236285 0.28072213 0.47589584]
 [0.08756867 0.13168989 0.2543299  0.24733803 0.94500576 0.26691237
  0.5854412  0.74681299 0.31905399 0.15442844]
 [0.08871779 0.43562753 0.69798846 0.8375329  0.64747944 0.73282585
  0.45798609 0.37906689 0.53697123 0.70746728]
 [0.46161355 0.8095659  0.08932425 0.59504584 0.31226617 0.87358596
  0.36291152 0.00843609 0.33110434 0.17115655]
 [0.63137153 0.88785808 0.97980617 0.8612494  0.28150607 0.99726076
  0.78024654 0.13630351 0.38188767 0.13558668]
 [0.84413499 0.52808706 0.09582013 0.91890042 0.65464975 0.65566097
  0.51127118 0.71740477 0.94094572 0.18541422]
 [0.36906741 0.70979417 0.48358149 0.98244035 0.7906496  0.40821067
  0.91770986 0

## 6. Create a random vector of size 30 and find the mean value.


In [8]:
vector = np.random.random((5,6))
np.mean(vector)

0.5678602702087511